/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.manager;

import com.conf.MyDatabase;
import com.manager.AccountManager;
import com.model.UserInfo;
import com.socket.ServerFrame;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author tranngocdien
 */
public class AccountManagerFrame extends javax.swing.JFrame {

    public AccountManager accountMng;
    ServerFrame serverFrameUi;
    
    /**
     * Creates new form AccountManageFrame
     */
    public AccountManagerFrame(ServerFrame serverFrameUi) {
        this.serverFrameUi = serverFrameUi;
        this.accountMng = new AccountManager(this, serverFrameUi.server.dbManager.db);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAcc = new javax.swing.JTable();
        btnAddAcc = new javax.swing.JButton();
        btnEditAcc = new javax.swing.JButton();
        btnDeleteAcc = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Hiển thị dữ liệu tìm kiếm");

        jLabel2.setText("Nhập thông tin tìm kiếm");

        btnSearch.setText("Tìm kiếm");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        tblAcc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Tk", "Mật khẩu", "Nhân viên", "Ngày tháng", "Họ tên", "Public key"
            }
        ));
        jScrollPane1.setViewportView(tblAcc);

        btnAddAcc.setText("Thêm");
        btnAddAcc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddAccActionPerformed(evt);
            }
        });

        btnEditAcc.setText("Sửa");
        btnEditAcc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditAccActionPerformed(evt);
            }
        });

        btnDeleteAcc.setText("Xoá");
        btnDeleteAcc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteAccActionPerformed(evt);
            }
        });

        jLabel3.setText("Chức năng");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jSeparator2))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnSearch))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(79, 79, 79)
                                        .addComponent(btnAddAcc)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnEditAcc)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnDeleteAcc)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(17, 17, 17))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnSearch))
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditAcc)
                    .addComponent(btnAddAcc)
                    .addComponent(btnDeleteAcc))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        try {
            // TODO add your handling code here:
            accountMng.find();
        } catch (Exception ex) {
            Logger.getLogger(AccountManagerFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnAddAccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddAccActionPerformed
        // TODO add your handling code here:
        MyDialog d = new MyDialog(this, MyDialog.DIALOG_ADD);
        d.setLocation(this.getLocation());
        d.setVisible(true);
    }//GEN-LAST:event_btnAddAccActionPerformed

    private void btnEditAccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditAccActionPerformed
        // TODO add your handling code here:
        System.out.println("Selected row index: " + tblAcc.getSelectedRow());
        System.out.println("Selected count: " + tblAcc.getSelectedRowCount());
        int selectCount = tblAcc.getSelectedRowCount();
        
        if(selectCount == 0) {
            JOptionPane.showMessageDialog(this, "Chọn account muốn thay đổi thông tin..", "WARNING.", JOptionPane.WARNING_MESSAGE);
        } else if  (selectCount > 1) {
            JOptionPane.showMessageDialog(this, "Chọn một account muốn thay đổi thông tin.", "WARNING.", JOptionPane.WARNING_MESSAGE);
        } else {
            // thay doi
            MyDialog d = new MyDialog(this, MyDialog.DIALOG_UPDATE);
            d.setLocation(this.getLocation());
            // get selected row data
            Object data[] = accountMng.getRowAt(tblAcc.getSelectedRow());
            int id = Integer.parseInt((String)data[0]);
            String username = (String)data[1];
            String password = (String)data[2];
            String employee = (String)data[3];
            String date = (String)data[4];
            String employeeName = (String)data[5];
            String publicKey = (String)data[6];
            d.initFields(new UserInfo(id, username, password, employee, date, employeeName, publicKey));
            d.setVisible(true);
        }
    }//GEN-LAST:event_btnEditAccActionPerformed

    private void btnDeleteAccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteAccActionPerformed
        // TODO add your handling code here:
        System.out.println("Selected row index: " + tblAcc.getSelectedRow());
        System.out.println("Selected count: " + tblAcc.getSelectedRowCount());
        int selectCount = tblAcc.getSelectedRowCount();
        
        if(selectCount == 0) {
            JOptionPane.showMessageDialog(this, "Chọn account muốn xoá", "WARNING.", JOptionPane.WARNING_MESSAGE);
        } else {
            int reply = JOptionPane.showConfirmDialog(null, "Bạn muốn xoá tài khoản đã chọn ?", "Xoá tài khoản",  JOptionPane.YES_NO_OPTION);
            if (reply == JOptionPane.YES_OPTION)
            {
                System.out.println("Yes");
                int rows[] = tblAcc.getSelectedRows();
                
                String ids = "";
                for (int i = 0; i < rows.length; i++) {
                    if(i>0) {
                        ids += ",";
                    }
                    ids += this.tblAcc.getValueAt(rows[i], 0);
                }
                try {
                    this.accountMng.delete(ids);
                    
                    // update table list
                    this.accountMng.clearAccountTable();
                    this.accountMng.fillList();
                } catch (SQLException ex) {
                    Logger.getLogger(AccountManagerFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                System.out.println("No");
            }
        }
    }//GEN-LAST:event_btnDeleteAccActionPerformed

    /**
     * @param args the command line arguments
     */
    public  void maina(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AccountManagerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AccountManagerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AccountManagerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AccountManagerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AccountManagerFrame(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddAcc;
    private javax.swing.JButton btnDeleteAcc;
    private javax.swing.JButton btnEditAcc;
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    public javax.swing.JTable tblAcc;
    public javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
